**1**

In [ ]:
import numpy as np

nparr = np.array([[1,2,3,4,6],[5,2,3,6,1],[1,7,8,4,4],[5,4,3,4,7]])
print(nparr)

[[1 2 3 4 6]
 [5 2 3 6 1]
 [1 7 8 4 4]
 [5 4 3 4 7]]


**2**

In [ ]:
import numpy as np

mat1 = np.random.randint(0,10,(4,5))
print(mat1)

[[6 6 4 8 7]
 [1 5 5 7 7]
 [0 2 4 5 2]
 [2 5 7 4 2]]


**3**

In [ ]:
import numpy as np
arr = np.array([[3,4],[1,2]])
print("Original matrix")
print(arr)
print()
print("Transpose matrix")
print(arr.T)
print()
print("determinant : ",int(np.linalg.det(arr)))

Original matrix
[[3 4]
 [1 2]]

Transpose matrix
[[3 1]
 [4 2]]

determinant :  2


**4**

In [ ]:
import numpy as np
mat = np.random.randint(0,10,(5,4))
print(mat)

[[7 1 4 7]
 [7 9 6 2]
 [0 9 1 4]
 [5 5 4 8]
 [3 3 1 0]]


**5**

In [ ]:
import numpy as np
mat1 = np.random.randint(0,10,(4,5))
mat2 = np.random.randint(0,10,(5,4))
print("Mat1")
print(mat1)
print()
print("Mat2")
print(mat2)

print()
print("Resultant of multiplication")
res  = np.matmul(mat1, mat2)
print(res)


Mat1
[[8 4 8 9 5]
 [6 0 8 3 8]
 [7 8 3 0 7]
 [9 0 0 5 8]]

Mat2
[[8 9 1 0]
 [3 6 9 8]
 [8 5 0 2]
 [9 8 4 5]
 [9 1 4 6]]

Resultant of multiplication
[[266 213 100 123]
 [211 126  50  79]
 [167 133 107 112]
 [189 129  61  73]]


**6**

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
res2 = a * b
print(res2)

[[ 1  4]
 [ 9 16]]


**7**

In [ ]:
import numpy as np
arr = np.array([[1,2],[7,4]])
mean = np.mean(arr)
med = np.median(arr)
print("Mean : ",mean)
print("Median : ",med)

Mean :  3.5
Median :  3.0


**8**

In [ ]:
matr = np.array([[2,3,5,6],[6,7,11,13],[1,9,19,23]])
print(matr[0:,1])

[3 7 9]


**9**

In [ ]:
import pandas as pd
iris = pd.read_csv('/Iris.csv')
iris.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

**10**

In [ ]:
import numpy as np 
matr = np.array([[1,2,3,4],[5,6,7,8]]) 
print (matr.shape)
matr2= matr.reshape(4,2)
print(matr2)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
